l_english:
 civic_tooltip_environmentalist_effects:1000 "£job_waste_manager£ $job_waste_manager_plural$ produce §G+2§! £unity£ §Y$unity$§!\n£job_waste_handler£ $job_waste_handler_plural$ produce §G+1§! £unity£ §Y$unity$§!\n£job_park_ranger£ $job_park_ranger_plural$ produce §G+1§! £unity£ §Y$unity$§!"
